name: Run scanner

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

permissions:
  contents: write
  actions: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      cache-key: crawler-cache-shizuku

    steps:
    - uses: actions/checkout@v3
      with:
        repository: thepbone/app-crawler

    - uses: actions/checkout@v3
      with:
        repository: thepbone/awesome-shizuku
        path: './list'
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: cache/
        key: ${{ env.cache-key }}
    
    - name: Run crawler
      env: 
        GITHUB_AUTH: ${{ secrets.GH_PAT }}
        SUMMARY_FILE: "list/pages/TODO.md"
      run: |
        python main.py ./list
        cat ./list/pages/TODO.md >> $GITHUB_STEP_SUMMARY

    - name: Delete previous cache
      if: ${{ steps.cache-restore.outputs.cache-hit }}
      continue-on-error: true
      run: |
          cd list/
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "${{ env.cache-key }}" --confirm
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Save cache
      uses: actions/cache/save@v3
      with:
        path: cache/
        key: ${{ env.cache-key }}

    - name: Publish summary changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repository: ./list
        commit_message: Update TODO.md
        file_pattern: pages/TODO.md

        
